version: 2.1

jobs:

  deploy:
    docker:
      - image: circleci/python:2.7
    parameters:
      deploy_environment:
        type: string
        default: common
      deploy_region:
        type: string
        default: us-west-2
    steps:
      - run:
          name: Deploying with runway
          working_directory: /
          no_output_timeout: 30m
          environment:
            CI: true
          command: |
            export PATH=$PATH:$HOME/.local/bin
            pip install --user pipenv
            pipenv install --skip-lock
            ./runway.yml.sh << parameters.deploy_region >> > runway.yml
            make deploy-<< parameters.deploy_environment >>

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          name: deploy_common
          deploy_environment: common
          deploy_region: us-west-2
          filters:
            branches:
              only:
                - master
      - deploy:
          name: deploy_demo
          deploy_environment: demo
          deploy_region: us-west-2
          filters:
            branches:
              only:
                - ENV-demo
      - deploy:
          name: deploy_prod
          deploy_environment: prod
          deploy_region: us-west-2
          filters:
            branches:
              only:
                - ENV-prod
