version: 2.1

jobs:
  build:
    executor: basic_image
    parameters:
      deploy_environment:
        type: string
      deploy_region:
        type: string
    steps:
      - run:
          name: Deploying with runway
          working_directory: runway/
          no_output_timeout: 30m
          environment:
            CI: true
          command: |
            export PATH=$PATH:$HOME/.local/bin
            pip install --user pipenv
            pipenv install --skip-lock
            ./runway.yml.sh << parameters.deploy_region >> > runway.yml
            DEPLOY_ENVIRONMENT=<< parameters.deploy_environment >> pipenv run runway deploy
workflows:
  build:
    jobs:
      - build
      - deploy:
          name: deploy_common
          deploy_environment: common
          deploy_region: us-west-2
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          name: deploy_demo
          deploy_environment: demo
          deploy_region: us-west-2
          requires:
            - build
          filters:
            branches:
              only:
                - ENV-demo
      - deploy:
          name: deploy_prod
          deploy_environment: prod
          deploy_region: us-west-2
          requires:
            - build
          filters:
            branches:
              only:
                - ENV-prod
